package-lock.json
package.json
yarn.lock

latest version of **babel-eslint 10.x** supports decorators
- bump minor version
- updating dependencies

chore(v1.4.1): update dependencies

---

config/eslint.config.js
package.json

- bump patch version to 1.4.**2**
- allows us to do
```js
@syntaticSugar
@withRouter
@connect()
export class
```

fix(legacy decorator support): allows to stack decorators before export

---

.editorconfig
config/editorconfig.config.rc
src/config.js

Adds an editorconfig file that matches the settings for prettier. This allows your editor to pick up on the whitespace (etc.) settings for a repo, so there won't be a mismatch for your indentation.
Don't know what you want the file in source to be called. I assumed `editorconfig.config`, but let me know if you prefer otherwise.

Add editorconfig

---

.travis.yml
src/cmds/js_cmds/check.js

This allows the style check to be used in as a CI status indicator (as done here in `.travis.yml`)

feat: set an exit code if js check fails

---

src/cmds/js_cmds/apply.js
src/cmds/js_cmds/check.js
src/files.js

Also stops users from manually passing in `.css`, `.json`, `.md` to prettier by specifying the files as arguments.
Fixes #20

fix: clean up js filter mechanism

---

README.md
src/cmds/js_cmds/apply.js
src/cmds/js_cmds/install.js

Instead of auto-installing config files (`.prettierrc.js`, `.browserslistrc`, `.editorconfig`) whenever applying styles (which could be at an arbitrary working directory) install them explicitly with a separate command `d2-style js install`.
Future work:
1. Find-up to get to the nearest `package.json` when installing, rather than using the working directory.
2. Warn of out-of-date configuration when applying styles

feat: stop auto-install of prettier and other config files

---

package.json
yarn.lock

For consistency, use the same version of @dhis2/cli-helpers-engine as we use in `cli`

chore: upgrade @dhis2/cli-helpers-engine

---

src/tools/js/eslint.js
src/tools/js/index.js
src/tools/js/prettier.js

This has the primary benefit of letting this instance of ESLint run in isolation from the [ESLint configuration cascade and hierarchy](https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) which can interfere with these standards.
Using only the linter and dealing with the output explicitly allows a project to have a local instance of ESLint for e.g. React 16.8 linting and cli-style for complying with DHIS2 code standards.
This has a secondary benefit of being faster. For maintenance app a full check went from **9.8 sec** to **7.2 sec**.

fix: use eslint linter instead of the cli engine

---

package.json
yarn.lock

This effects a very minor in-range dependency update which shouldn't need its own version bump in `cli-style`, so I'm leaving this as a `chore`

chore: pin cli-helpers-engine, support greenkeepr updates

---

package.json
yarn.lock

MINOR: A direct `yargs` dep is not required - we always get it passed as a function argument from `cli-helpers-engine`.  This should help reduce unnecessary dependabot PRs

chore: remove direct yargs dep

---

src/tools/eslint.js

This overrides any ignores placed in a local .eslintignore file
and thus makes it impossible to ignore hidden files with eslint.

fix(eslint): do not add an unignore pattern to the cli command

---

config/js/eslint.config.js
docs/_sidebar.md
docs/overrides.md
package.json
src/commands/javascript.js
src/commands/structured-text.js
src/tools/eslint.js
yarn.lock

This cleans up the log messages and reports that `d2-style js check`
prints:
Before the ESLint and Prettier commands run separately, which is kind of
nice from a technical standpoint of separation, but leads to situations
where we have to first fix the ESLint problems:
```
varl@veronika:~/dev/dhis2/libs/cli-style$ ./bin/d2-style js check
d2-style > javascript
/home/varl/dev/dhis2/libs/cli-style/src/index.js
3:7  error  'foo' is assigned a value but never used  no-unused-vars
✖ 1 problem (1 error, 0 warnings)
```
And then run `js check` again only to get:
```
varl@veronika:~/dev/dhis2/libs/cli-style$ ./bin/d2-style js check
d2-style > javascript
src/index.js
[WARNING] Code style issues found in the above file(s).
```
Not too much information about _what_ issues it found either. We can …

feat: use eslint to run prettier

---

config/js/eslint-react.config.js
package.json
yarn.lock

This adds a rule to detect unused modules (both unused exports, and modules without exports). See this PR: https://github.com/dhis2/scheduler-app/pull/45, where I've added it for the scheduler (alongside with other rules).
I've added a pattern to ignore tests, but if other patterns pop up of files that should always be ignored we should add them under `ignoreExports`.
See: https://github.com/benmosher/eslint-plugin-import
---
Besides the no-unused-modules rule, in the linked PR I've also added rules to check whether imported modules (default and named imports) exist, cyclical dependency checking, import prettifying (sorting, consistent use of extensions, etc.) and deep import blocking. Quite useful in my opinion. Especially the checking of whether imports exist or not is very nice to have …

feat(eslint): add no-unused-modules rule

---

config/js/eslint-react.config.js
config/js/eslint.config.js
docs/overrides.md

This switches to the recommended settings for the eslint import plugin. Their presets are rather conservative (but still very useful), so there shouldn't be anything in here that has to be overridden.
It doesn't add the no-cycle rule, as that rule can be quite resource intensive (it lints node_modules as well by default). We could enable it and ignore node_modules. Then apps could always enable linting that as well if they want it.
Furthermore, this removes the no-unused-modules rule. Viktor and I talked about it in #248. Our conclusion there was to require the user to set ignoreExports (the recommendation in the linked issue). However, if the user has to set that, due to the structure of the rule they basically have to redefine the entire rule anyway. So our shipping the rule isn't very …

fix(eslint-import): switch to recommended import settings

---

docs/faq.md

This clarifies the requirements husky has for node and git. The errors when husky fails can get drowned out in the install process, so this is a gotcha for our users.
See: https://dhis2.slack.com/archives/C0BP0RABF/p1588840822444100

docs(husky): add husky requirements to docs

---

docs/getting-started.md
package.json
src/commands/install.js
yarn.lock

When running `d2 style install` without arguments, an interative prompt
displaying the available projects is displayed:
```
$ d2-style install
? Choose the project template (Use arrow keys)
❯ base
js
react
```
To install a custom set of groups, it works the same as before. The
groups are not displayed in the prompt to guide the user to make a safe
choice.
The full list can be seen with `--list-groups` and multiple groups can
be passed in as a space separated list as before.
This feature is kept small and simple in scope to avoid the temptation
to refactor how projects and groups function and tackle that as a
separate task.

feat(install): prompt to choose project from list

---

.github/workflows/dhis2-verify-node.yml
src/utils/files.js

This fixes instances where there are staged changes, but they aren't
picked up with using the `--staged` flag.
After moving to gathering files with absolute paths, we must construct
absolute paths for the files reported as changed by Git that were listed
as relative.

fix: resolve relative paths to staged files

---

README.md
config/git/hooks/commit-msg
docs/faq.md
docs/getting-started.md
docs/migrate-guide.md
src/commands/install.js
src/utils/groups.js
src/utils/paths.js
tests/group-resolution.js

- chore: add config for commit-msg hook
- fix: make hook suitable for other repos
- feat: opt-in to use git-hooks with install

feat: opt-in git hooks

---

config/js/eslint.config.js
docs/faq.md
src/tools/commitlint.js
src/tools/eslint.js

This removes the `--quiet` flag from the ESLint invocation, and fixes
the broken output where ESLint complains about us trying to lint
dot-files and folders by un-ignoring their built-in ignore filters.
We agree with ignoring node_modules in terms of linting however, so that
is left in place.
Supersedes: #367 
Supersedes: #366

feat: show eslint warnings

---

config/d2-style.config.js
package.json
src/commands/types/javascript.js
src/commands/types/structured-text.js
src/utils/files.js
yarn.lock

Allows the user to pass directory, filenames, and globs to the "check"
and "apply" commands:
yarn d2-style check *.js
yarn d2-style check .
yarn d2-style check src
yarn d2-style check src/**/*.spec.js
Note that the first example "*.js" means that basename matching is
enabled so that if a file has a '/' in the path, it will still be a
successful match.
This allows us to simplify the patterns in d2style.config.js by saying
that:
patterns.js = '*.js'
Instead of:
patterns.js = '**/*.js'
On the question why we aren't just passing along the argument as-is to
eslint and prettier (they support "dir|file|glob" in their clis) the
answer is two-fold:
1.  We want to control which files are passed to the tool to avoid
e.g. Prettier checking non-js files that it supports when we run
"check js" for …

feat: improve file name matching

---

src/commands/install.js
src/commands/types/commit.js
src/utils/files.js
src/utils/git.js
src/utils/paths.js

Introduce a gitEnabled() function used to identify if Git operations
like linting commits and installing hooks should be done.
Modifies how the PROJECT_ROOT is identified when there is no .git
directory by adding additional root-level files like yarn.lock and
package-lock.json.
Jira-Issue: CLI-43

fix(cli-43): skip git ops when not a git repo

---

src/commands/actions/editorconfig.js
src/commands/actions/git-hook.js
src/commands/actions/github.js
src/commands/actions/ls-lint.js
src/commands/actions/prettier.js
src/tools/husky.js
src/utils/config.js
src/utils/files.js

This adds support for more tools:
- EditorConfig
- Prettier
- ls-lint
- GitHub
- Stale
- Dependabot
- Semantic Pull Requests
- Workflows
- NodeJs
- App
- Lib
Now uses the cli-helpers-engine cache to download the workflows directly
from dhis2/workflows.

feat(tools): adds add/remove commands for tools

---

package.json
yarn.lock

BREAKING CHANGE: New minimum version for NodeJS is 12.x.

chore: remove node 10 support

---

src/commands/check.js

Provide a log message when the `apply` and `check` commands fail that make it clear that all checks did not pass.
When running `check`:
```sh
javascript > eslint 
/home/varl/dev/dhis2/cli/style/src/commands/types/javascript.js
12:1   error  Function 'foo' has too many parameters (4). Maximum allowed is 3  max-params
12:10  error  'foo' is defined but never used                                   no-unused-vars
12:14  error  'fuz' is defined but never used                                   no-unused-vars
12:19  error  'buz' is defined but never used                                   no-unused-vars
12:24  error  'fiz' is defined but never used                                   no-unused-vars
12:29  error  'biz' is defined but never used                                   no-unused-vars
✖ 6 …
```

fix: print summary error message

---

config/eslint.config.js

This will enforce explicit imports. Unfortunately there doesn't seem to be any auto fixing.
See [this Slack thread](https://dhis2.slack.com/archives/CPGUFVC56/p1624366840180000) for more background info.

feat(eslint): enforce file extensions within the import path

---

.ls-lint.yml
templates/ls-lint-base.yml

I have tested this a bit and I think it will pick up bad file names correctly in most cases. However, there is still a problem for monorepos, for example `./package-name/node_modules/src/BAD_FILE.js` is still going to be flagged up as a violation.
I tried adding an ignore line with a glob to combat this, but this didn't seem to have any effect:
```
ignore:
- node_modules
- ./**/node_modules
```
Explicitely ignoring the `node_modules` folder did have the desired effect though: 
```
- node_modules
- package-name/node_modules
```
Since we can't know the package names upfront, I think we simply need to accept that some manual attention will be required for monorepos.

fix(ls-lint): improve configuration template to fit most projects

---

package.json
yarn.lock

Bump ls-lint to 1.10.0 to avoid an error on arm64 cpus

fix: bump ls-lint

---

config/eslint-react.config.js

This adds config for the react-hooks eslint plugin. The plugin already ships with CRA, so all I've done is enable it:
I've set exhaustive-deps to warn. Initially there were some false positives for this rule that meant an error wasn't always correct: https://github.com/facebook/react/issues/14920. Though that issue has since been closed, so maybe it's safe to set to error. There are some related issues open: https://github.com/facebook/react/issues?q=is%3Aissue+is%3Aopen+exhaustive, but maybe setting it to error and just expecting the user to disable when necessary is good enough.

feat(eslint): add react hooks plugin configuration

---

src/utils/config.js

This moves the commit linting preset to the new workflow that was added to https://github.com/dhis2/workflows.

fix: move commit linting to separate workflow

---

package.json
yarn.lock

Noticed that this was missing a dependency `eslint-plugin-react-hooks`, but it was hidden since it was piggy-backing on the dependency from `react-scripts`. In the platform, after removing `react-scripts`, this failed to run (see `git` logs below).
Adding the plugin as a dev dependency in the platform repo fixed it, so I'm confident adding the dep in here will fix it for consumers 👍 
```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
yarn run v1.22.19
$ /Users/kai/dev/dhis2/app-platform/node_modules/.bin/d2-style check --staged
javascript > eslint 
Oops! Something went wrong! :(
ESLint: 7.32.0
ESLint couldn't find the plugin "eslint-plugin-react-hooks".
(The package "eslint-plugin-react-hooks" was not found when loaded as a Node module from the directory …
```

fix: add missing dep for eslint-plugin-react-hooks

---

docs/getting-started.md

This updates cli-style documentation to mention stylelint in getting started guide.

chore: mention stylelint in docs

---

config/eslint-react.config.js

If file extensions aren't used for some reason (workspace preference, for example), ESLint can show an error like `Unable to resolve path to module './components/Routes'` when trying to import from `./components/Routes.jsx`. This config change fixes the resolver
I think for .tsx files, that's handled by the typescript config
Example of before and after, using local ESLint config:

fix(eslint-react-config): handle files with .jsx extensions
